### PR TITLE
Buggy-API

### PR DESCRIPTION
**Pull request by Anant-Gaikwad**
Removed duplicate insert scripts from db xml file, which causes primary key violations while starting applications.
After that I have verified both users can login.

### CODE REVIEW

**Review by parikshitd-webonise — CHANGES_REQUESTED** [review]
This will not solve the problem. I am still able to insert duplicate. Need more changes to solve the issue.

**Comment by Anant-Gaikwad** [comment]
> This will not solve the problem. I am still able to insert duplicate. Need more changes to solve the issue.

Actually i have not understood problem statement. Can you please explain the problem.
After application starts up, Now i'm able to login with both users.

**Comment by parikshitd-webonise** [comment]
The app when it comes up will have 2 users created in the system -

user1@gmail.com with password user1ABC
user2@gmail.com with password user2ABC
user1@gmail.com cant login but user2@gmail.com can

The output expected out of this is as follows
Debug why the login for user1@gmail.com fails.
Once the bug is discovered fix it and submit the assignment via git 
This fix should be a firm fix not patch code. Do all changes which are required.

**Comment by Anant-Gaikwad** [comment]
> The app when it comes up will have 2 users created in the system -
> 
> [user1@gmail.com](mailto:user1@gmail.com) with password user1ABC
> [user2@gmail.com](mailto:user2@gmail.com) with password user2ABC
> [user1@gmail.com](mailto:user1@gmail.com) cant login but [user2@gmail.com](mailto:user2@gmail.com) can
> 
> The output expected out of this is as follows
> Debug why the login for [user1@gmail.com](mailto:user1@gmail.com) fails.
> Once the bug is discovered fix it and submit the assignment via git
> This fix should be a firm fix not patch code. Do all changes which are required.

But i'm able to login using both user. There is no error while login. That's the reason i did not understood problem statement.

**Comment by parikshitd-webonise** [comment]
What if I insert the duplicate records again. Your code does not have any error handling r constraints. We need to again delete duplicate entries and that's not an optimized solution.

**Review by parikshitd-webonise — CHANGES_REQUESTED** [review]
I can still insert duplicate, And also there are not guarantee that which login details will be returns, Also we should not return list because login should be unique. This is not a potential bug fix.

**Pull request closed without merging**
